name: Test
on:
  push:
  pull_request:
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16]
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - name: Derive appropriate SHAs for base and head for `nx affected` commands
        uses: nrwl/nx-set-shas@v2
      - name: Cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
          restore-keys: cache-node-modules-${{ hashFiles('pnpm-lock.yaml') }}
      - run: pnpm nx affected --target=test